# -*- coding: utf-8 -*-
"""Global_rescoring_v3_Fabio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLDRbRoPPia2jlpHaGzEsPt9stUBgkPG
"""



"""# Global interaction ranking L"""



#pip install rdkit
import re
import numpy as np
import os
import math
from rdkit import Chem
from rdkit.Chem import AllChem

"""
1.   extract atomic info: atom_ID, element, x, y, z
2.   extract bonding info: atom_ID 1, atom_ID 2, bond order"""

parameter = input("parameter file: ")
pa = open(parameter,"r")

# extracting all numeric parameters and appending them to (para: list)
para = []
for line in pa:
  match = re.search(":", line)
  # if there's a colon, extract the number
  if match:
    num = re.split(': |\n', line)[1]
    para.append(float(num))

def extract(input,type):
  """
  Parse molecular coordinate and connectivity lines into structured arrays.

  Parameters
  ----------
  input_lines : list of str
    Lines of text representing atoms, bonds, and rings from a coordinate file.
  mode : str
    Parsing mode: 'target' to extract atoms and bonds for a target molecule;
    'ligand' to extract atoms, bonds, and ring definitions for a ligand.

  Returns
  -------
  atom : numpy.ndarray
    For 'target': array of shape (N, 5) with columns [atom_index, atom_type, x, y, z].
    For 'ligand': array of shape (N, 5) with columns [atom_id, atom_type, x, y, z].
  bond : numpy.ndarray
    Array of shape (M, 3) with columns [atom1_index, atom2_index, bond_order].
  ring : list of list of str or None
    Only in 'ligand' mode: a list of ring definitions (each a list of strings).
    None for 'target' mode.

  Notes
  -----
  - Uses regular expressions to identify atom, bond, and ring lines.
  - Coordinates are cast to floats; indices and bond orders to integers.
  """
  # parsing behaviour 1: target
  if type == "target":
    atom = np.empty((0, 5))
    bond = np.empty((0, 3))

    # iterates line by line
    for coor in input:
      # matching against the pattern below1 -> line represents an atom
      match1 = re.search(r"\s\d+\s[A-Za-z*]+\s[-]?\d+[.]?\d?\d?\d?\d?",coor)
      if match1:
        info = coor.split()
        # info[2]=atom index; info[3]=atom type; info[4],info[5],info[6]=X,Y,Z
        atom = np.append(atom, np.array([[int(info[2]), info[3], float(info[4]), float(info[5]), float(info[6])]]), axis=0)

      # matching against different pattern2 -> line represents bond line
      match2 = re.search(r"^\D\s+\S+\s\d+\s\d\s\d+\s\d+$",coor)
      if match2:
        info = coor.split()
        # info[4],info[5]=atom indices which bond connects; info[3]=bond order
        bond = np.append(bond, np.array([[int(info[4]), int(info[5]), int(info[3])]]), axis=0)
    return atom, bond

  # parsing behaviour 2: ligand
  if type == "ligand":
    atom = np.empty((0, 5))
    bond = np.empty((0, 3))
    ring = []
    # counter for atom numbering
    id = 0
    for coor in input:
      # matching against pattern1 below -> line represents an atom line
      match1 = re.search(r"\S+\S+\s+\S+\S+\s+\S+\S+\s\D",coor)
      if match1:
        id += 1
        info = coor.split()
        # info[3]=atom type; info[0],info[1],info[2]=X,Y,Z
        atom = np.append(atom, np.array([[int(id), info[3], float(info[0]), float(info[1]), float(info[2])]]), axis=0)

      # matching against pattern2 below -> line represents a bond line
      match2 = re.search(r"^\s*\d+\s+\d+\s+[1-9]\s+\d\s+",coor)
      if match2:
        info = coor.split()
        # info[0],info[1]=atom indices which bond connects; info[2]=bond order
        bond = np.append(bond, np.array([[int(info[0]), int(info[1]), int(info[2])]]), axis=0)

      # matching against pattern3 below -> line represents a ring definition line
      match3 = re.search(r" - \d+ - \d+ - \d+",coor)
      if match3:
        del info[-2:]
        info = coor.split(' - ')
        ring.append(info)
    return atom, bond, ring

"""1. classify HBDAs and metals (strong donor (+metals), normal donor, weak donor, strong acceptor, normal acceptor)
2. classify pi-components (sp2 atoms and non-sp2 N/O/S with lone pairs)
"""

def bonding(atom_id, atom2, bond2):
  """
  Compute bonding information for a given atom.

  Parameters
  ----------
  atom_id : int
    The ID of the atom for which to gather bonding data.
  atom2 : ndarray of shape (N, 5)
    Array of atom records; each row is [ID, element, x, y, z].
  bond2 : ndarray of shape (M, 3)
      Array of bond records; each row is [atom1_ID, atom2_ID, bond_order].

  Returns
  -------
  total : int
    Sum of bond orders around the specified atom.
  bound_atom : ndarray of str
    Element symbols of atoms directly bonded to atom_id.
  bound_id : ndarray of int
    Numeric IDs of atoms directly bonded to atom_id.
  bound_atom_count : int
    Number of atoms bonded to atom_id.
  """
  # sum of bond orders around atom_id
  total = 0

  bound_atom = np.empty(0) # elements of bound atoms
  bound_id = np.empty(0) # ID of bound atoms
  # iterates through the bond entries
  for i in range(len(bond2)):
    # if bond involves target atom -> add bond order to total
    if int(bond2[i][0]) == atom_id or int(bond2[i][1]) == atom_id:
      total += int(bond2[i][2])
      # append the atom on the other end of the bond to bound_atom and bound_id lists
      if int(bond2[i][0]) == atom_id:
        bound_atom = np.append(bound_atom, atom2[int(bond2[i][1]) - 1][1])
        bound_id = np.append(bound_id, atom2[int(bond2[i][1]) - 1][0])
      else:
        bound_atom = np.append(bound_atom, atom2[int(bond2[i][0]) - 1][1])
        bound_id = np.append(bound_id, atom2[int(bond2[i][0]) - 1][0])
  bound_atom_count = len(bound_atom) # summing number of bound atoms
  return total, bound_atom, bound_id, bound_atom_count


def classify(atom,bond):
  """
  Classify each atom in a molecule according to hydrogen-bonding and conjugation roles.

  Parameters
  ----------
  atom : ndarray of shape (N, 5)
    Array of atom records; each row is [ID, element, x, y, z].
  bond : ndarray of shape (M, 3)
    Array of bond records; each row is [atom1_ID, atom2_ID, bond_order].

  Returns
  -------
  SD : ndarray of int
    Atom IDs classified as strong hydrogen-bond donors.
  ND : ndarray of int
    Atom IDs classified as normal hydrogen-bond donors.
  WD : ndarray of int
    Atom IDs classified as weak hydrogen-bond donors.
  SA : ndarray of int
    Atom IDs classified as strong hydrogen-bond acceptors.
  NA : ndarray of int
    Atom IDs classified as normal hydrogen-bond acceptors.
  sp2 : ndarray of int
    Atom IDs of sp²-hybridized centers.
  lone : ndarray of int
    Atom IDs that possess a lone pair (e.g. OH, NH₂).
  """
  SD = np.empty(0) # strong donors
  ND = np.empty(0) # normal donors
  WD = np.empty(0) # weak donors
  SA = np.empty(0) # strong acceptors
  NA = np.empty(0) # normal acceptors
  XX = np.empty(0) # heavy atoms which aren’t classified as donors/acceptors.
  sp2 = np.empty(0) # sp² centers
  lone = np.empty(0) # lone pair atoms
  conjR = np.empty(0) # conjugatable R=R
  conj_N = np.empty(0) # conjugated nitrogens

  # iterates through atom list
  for j in range(len(atom)):
    # C or P
    if atom[j][1] == 'C' or atom[j][1] == 'P': # carboxylates, phosphates
      # initialise new list "conj_O" to collect candidate oxygens
      conj_O = np.empty(0)
      ordersum, neighbor, neighbor_id, neighborsum = bonding(int(atom[j][0]), atom, bond)
      # iterate through current atom's neighbours
      for n in neighbor_id:
        # if neighbouring atom is oxygen
        if atom[int(n)-1][1] == 'O':
          nei_ordersum, nei_neighbor, nei_neighbor_id, nei_neighborsum = bonding(int(n), atom, bond)
          # if oxygen is bonded to exactly one atom -> append to "conj_0"
          if nei_neighborsum == 1:
            conj_O = np.append(conj_O, int(n))
      # if atom has >1 singly‐bound oxygen -> append atom to SA (strong acceptor) list
      if len(conj_O) > 1:
        for co in conj_O:
          SA = np.append(SA, str(int(co)))
          # carboxylic acid and phosphate conjugation ARE considered

    # handling unmarked O and S
    if (atom[j][1] == 'O' and atom[j][0] not in SA) or atom[j][1] == 'S':
      # similar computation as above for bonding info
      ordersum, neighbor, neighbor_id, neighborsum = bonding(int(atom[j][0]), atom, bond)
      if ordersum == 1:  # RO-, RS-
        # single bond only -> append atom to SA (strong acceptor) list
        SA = np.append(SA, atom[j][0])
      if ordersum == 2:
        if neighborsum == 1:  # R=O, R=S
          # double bond to one neighbour -> append atom to NA (normal acceptor) list
          NA = np.append(NA, atom[j][0])
          nei_ordersum, nei_neighbor, nei_neighbor_id, nei_neighborsum = bonding(int(atom[j][0]), atom, bond)
          for r in nei_neighbor_id:
            if r not in conjR:
              conjR = np.append(conjR, r) # conjugatable R=O, R=S
        if neighborsum == 2:  # ROR, RSR, ROH, RSH, H2O
          # two neighbours -> append to NA (normal acceptor) list && has a lone pair
          NA = np.append(NA, atom[j][0])
          lone = np.append(lone, atom[j][0])
          # if one neighbour is H, it can donate a H bond -> append to ND (normal donor) list
          if 'H' in neighbor:  # ROH, RSH, H2O
            ND = np.append(ND, atom[j][0])
            # sulfonium is not considered to be H-bond acceptor

    # F or Cl -> always NA (normal acceptor)
    if atom[j][1] == 'F' or atom[j][1] == 'Cl':  # R-F, R-Cl
      NA = np.append(NA, atom[j][0])

    # C
    if atom[j][1] == 'C':
      ordersum, neighbor, neighbor_id, neighborsum = bonding(int(atom[j][0]), atom, bond)
      # has at least one H and one electronegative neighbour -> weak donor
      if 'H' in neighbor:
        if 'O' in neighbor or 'N' in neighbor or 'F' in neighbor: # N/O/F-C-H
          WD = np.append(WD, atom[j][0])  # NCHB donors are considered the same regardless of the number/ charge of heteroatoms bound to the carbon
      # if bonded to 3 atoms -> sp²-hybridized so append C atom to conjR
      if neighborsum == 3:
        sp2 = np.append(sp2, atom[j][0])
        if atom[j][0] not in conjR:
          conjR = np.append(conjR, atom[j][0]) # other conjugatable C=X

    # N
    if atom[j][1] == 'N':
      ordersum, neighbor, neighbor_id, neighborsum = bonding(int(atom[j][0]), atom, bond)
      # if any of its neighbours are in conjR -> if so, append N atom to conj_N
      for n in neighbor_id:
        if n in conjR and atom[j][0] not in conj_N:
          conj_N = np.append(conj_N, atom[j][0]) # conjugated N:
      if ordersum == 3:  # R-CN, R=N-R, R=NH, R-NH2, R2NH, R3N
        # if three neighbors -> it has a lone pair
        if neighborsum == 3:  # R-NH2, R2NH, R3N
          lone = np.append(lone, atom[j][0])
          if atom[j][0] not in conj_N:
            NA = np.append(NA, atom[j][0]) # excluding cases with conjugated lone pair of N
        # if two neighbors -> normal acceptor & sp²
        if neighborsum == 2:  # R=N-R, R=NH
          NA = np.append(NA, atom[j][0])
          sp2 = np.append(sp2, atom[j][0])
        # if any H neighbor -> normal donor
        if 'H' in neighbor:  # R=NH, R-NH2, R2NH
          ND = np.append(ND, atom[j][0])
      # protenated N
      if ordersum == 4:
        # if H attached -> strong donor
        if 'H' in neighbor:  # R3NH+, R2NH2+, RNH3+, R2=NHR+
          SD = np.append(SD, atom[j][0])
        # if 3 neighbours ->  sp² center
        if neighborsum == 3:  # R=NR2+
          sp2 = np.append(sp2, atom[j][0])

    # certain metal ions -> strong donors
    if atom[j][1] in ['K', 'Na', 'Mg', 'Zn', 'Mn']:  # metals
      SD = np.append(SD, atom[j][0])

    # any unmarked heavy atom -> XX
    if (atom[j][0] not in SD and atom[j][0] not in ND and atom[j][0] not in WD and atom[j][0] not in SA and atom[j][0] not in NA) and atom[j][1] != 'H': # heavy atom of non-HBDAs
      XX = np.append(XX, atom[j][0])

  return SD, ND, WD, SA, NA, XX, sp2, lone

"""1. define spherical environment
2. H-bond, pi-stacking scoring and unsatisfied H-bond penalty

aromatic ring:
1. ONLY =?-, -O/S-, -NR-
2. at least three =?-
"""

def envir(x, t_atom):  # x is the targeted atom of ligand
  """
  Identify the “environment” of a ligand atom by finding all heavy atoms
  in the target (macromolecule) that lie within a given distance range.

  Parameters
  ----------
  x : array-like of length 5
    The ligand atom record [ID, element, x, y, z].
  t_atom : ndarray of shape (M, 5)
    Array of macromolecule atoms; each row is [ID, element, x, y, z].

  Returns
  -------
  env : ndarray of shape (K, 2)
    Each row is [ID, element] of a macromolecule atom whose
    distance from x is between para[1] and para[0].
  """
  env = np.empty((0, 2)) # environment list containing atom ID and corresponding element from macromolecule
  steric = np.empty((0, 1)) # environment list containing only atom ID --> for counting disfavorable interactions
  # iterate over atoms in macromolecule
  for line in t_atom:
    if line[1] != 'H': # only care about heavy atoms
      # calculating euclidean distance between the ligand atom 'x' and a macromolecule atom "line"
      r = np.linalg.norm(np.array([float(x[2]), float(x[3]), float(x[4])]) - np.array([float(line[2]), float(line[3]), float(line[4])]))
      # if r is within range [para[0], para[1]] -> append to environment
      if r <= para[0] and r >= para[1]:
        env = np.append(env, np.array([[line[0],line[1]]]), axis=0)
        if r <= para[2]:
          steric = np.append(steric, np.array([[line[0]]]), axis=0)

  return env, steric


def hbond_score(l_atom, t_atom, l_SD, l_ND, l_WD, l_SA, l_NA, l_XX, t_SD, t_ND, t_WD, t_SA, t_NA, t_XX):
  """
  Compute counts of hydrogen bonds, charged interactions, salt bridges, and unsatisfied donors/acceptors
  between ligand and target atoms.

  Parameters
  ----------
  l_atom : ndarray of shape (L, 5)
      Ligand atom records.
  t_atom : ndarray of shape (T, 5)
      Target atom records.
  l_SD, l_ND, l_WD, l_SA, l_NA, l_XX : array-like
      IDs of ligand atoms classified as strong donors, normal donors, weak donors,
      strong acceptors, normal acceptors, and non-HBDA heavy atoms.
  t_SD, t_ND, t_WD, t_SA, t_NA, t_XX : array-like
      Same classifications for the target.

  Returns
  -------
  total_hbond_count : int
      Total number of hydrogen‐bonding interactions found.
  charged_hbond_count : int
      Count of interactions involving charged donors/acceptors.
  salt_bridge_count : int
      Count of salt bridges (strong donor + strong acceptor).
  unsatisfied_count : int
      Number of donors/acceptors with no partner in range.
  """
  total_hbond_count = 0
  charged_hbond_count = 0
  salt_bridge_count = 0
  unsatisfied_count = 0

  # iterate over each ligand atom
  for l in l_atom:
    print_list = []
    sub_total_hbond_count = 0
    sub_charged_hbond_count = 0
    sub_salt_bridge_count = 0
    sub_unsatisfied_count = 0
    # getting neighbours in range
    env, steric = envir(l, t_atom)

    # (*) if ligand atom's is normal donor and normal acceptor
    if l[0] in l_ND and l[0] in l_NA:  # both normal donor and acceptor
      print_list.append(l[1] + "_" +  l[0] + " (both normal donor and acceptor):")
      # iterate through the ligand atom's neighbours
      for env_atom in env:
        # if neighbour's in t_NA, t_ND, t_SA, t_SD, or t_WD -> increment relevant sub-list
        if env_atom[0] in t_NA or env_atom[0] in t_ND or env_atom[0] in t_SA or env_atom[0] in t_SD or env_atom[0] in t_WD:
          sub_total_hbond_count += 1
          # append to print list
          print_list.append("interaction with " + env_atom[1] + "_" + env_atom[0])
          if env_atom[0] in t_SA or env_atom[0] in t_SD:
            sub_charged_hbond_count += 1
      # if env != empty but there were no interactions -> ligand atom marked as unsatisfied
      if sub_total_hbond_count == 0 and len(env) != 0:  # unsatisfied H-bond
        for en in env:
          if en[0] in steric:
            sub_unsatisfied_count += 1
            print_list.append("penalized for disfavored interaction with " + str(env))

    # for normal donor only -> similar to (*)
    if l[0] in l_ND and l[0] not in l_NA:  # normal donor only
      print_list.append(l[1] + "_" +  l[0] + " (normal donor only):")
      for env_atom in env:
        if env_atom[0] in t_NA or env_atom[0] in t_SA:
          sub_total_hbond_count += 1
          print_list.append("interaction with " + env_atom[1] + "_" + env_atom[0])
          if env_atom[0] in t_SA:
            sub_charged_hbond_count += 1
      if sub_total_hbond_count == 0 and len(env) != 0:  # unsatisfied H-bond
        for en in env:
          if en[0] in steric:
            sub_unsatisfied_count += 1
            print_list.append("penalized for disfavored interaction with " + str(env))

    # for normal acceptor only -> similar to (*)
    if l[0] not in l_ND and l[0] in l_NA:  # normal acceptor only
      print_list.append(l[1] + "_" +  l[0] + " (normal acceptor only):")
      for env_atom in env:
        if env_atom[0] in t_ND or env_atom[0] in t_SD or env_atom[0] in t_WD:
          sub_total_hbond_count += 1
          print_list.append("interaction with " + env_atom[1] + "_" + env_atom[0])
          if env_atom[0] in t_SD:
            sub_charged_hbond_count += 1
      if sub_total_hbond_count == 0 and len(env) != 0:  # unsatisfied H-bond
        for en in env:
          if en[0] in steric:
            sub_unsatisfied_count += 1
            print_list.append("penalized for disfavored interaction with " + str(env))

    # for strong donor only -> similar to (*)
    if l[0] in l_SD:  # strong donor
      print_list.append(l[1] + "_" +  l[0] + " (strong donor):")
      for env_atom in env:
        if env_atom[0] in t_NA or env_atom[0] in t_SA:
          sub_total_hbond_count += 1
          print_list.append("interaction with " + env_atom[1] + "_" + env_atom[0])
          if env_atom[0] in t_NA:
            sub_charged_hbond_count += 1
          if env_atom[0] in t_SA:
            sub_salt_bridge_count += 1
      if sub_total_hbond_count == 0 and len(env) != 0:  # unsatisfied H-bond
        for en in env:
          if en[0] in steric:
            sub_unsatisfied_count += 1
            print_list.append("penalized for disfavored interaction with " + str(env))

    # for strong acceptor only -> similar to (*)
    if l[0] in l_SA:  # strong acceptor only
      print_list.append(l[1] + "_" +  l[0] + " (strong acceptor only):")
      for env_atom in env:
        if env_atom[0] in t_WD or env_atom[0] in t_ND or env_atom[0] in t_SD:
          sub_total_hbond_count += 1
          print_list.append("interaction with " + env_atom[1] + "_" + env_atom[0])
          if env_atom[0] in t_ND or env_atom[0] in t_WD:
            sub_charged_hbond_count += 1
          if env_atom[0] in t_SD:
            sub_salt_bridge_count += 1
      if sub_total_hbond_count == 0 and len(env) != 0:  # unsatisfied H-bond
        for en in env:
          if en[0] in steric:
            sub_unsatisfied_count += 1
            print_list.append("penalized for disfavored interaction with " + str(env))

    # for weak donor only -> similar to (*)
    if l[0] in l_WD:  # weak donor (no penalty for not interacting)
      print_list.append(l[1] + "_" +  l[0] + " (weak donor):")
      for env_atom in env:
        if env_atom[0] in t_NA or env_atom[0] in t_SA:
          sub_total_hbond_count += 1
          print_list.append("interaction with " + env_atom[1] + "_" + env_atom[0])
          if env_atom[0] in t_SA:
            sub_charged_hbond_count += 1

    # for non_HBDAs only -> similar to (*)
    if l[0] in l_XX: # non-HBDAs
      print_list.append(l[1] + "_" +  l[0] + " (non-HBDAs):")
      bad_interaction_count = 0
      for env_atom in env:
        if env_atom[0] in t_NA or env_atom[0] in t_ND or env_atom[0] in t_SA or env_atom[0] in t_SD: # no penalty for interacting weak donors
          bad_interaction_count += 1
      if bad_interaction_count != 0 and len(env) != 0:
        for en in env:
          if en[0] in steric:
            sub_unsatisfied_count += 1
            print_list.append("penalized for disfavored interaction with " + str(env))

    # if print_list > 1 then print
    if len(print_list) > 1:
      for result in print_list:
        log.write(result + "\n")

    # update general counts for each iteration of the ligand atoms
    total_hbond_count += sub_total_hbond_count
    charged_hbond_count += sub_charged_hbond_count
    salt_bridge_count += sub_salt_bridge_count
    unsatisfied_count += sub_unsatisfied_count

  return total_hbond_count, charged_hbond_count, salt_bridge_count, unsatisfied_count


def find_ring(sdf_file, sp2, lone):
  """
  Identify fully aromatic rings in a molecule SDF.

  Parameters
  ----------
  sdf_file : str
      Path to an SDF file containing one or more molecules.
  sp2 : array-like
      (Not used) IDs of sp² atoms, perhaps for later filtering.
  lone : array-like
      (Not used) IDs of lone-pair atoms.

  Returns
  -------
  aromatic : list of tuples
      Each tuple contains 1-based atom IDs that form a fully aromatic ring.

  """
  aromatic = []

  """
  # load molecules from SDF
  supplier = Chem.SDMolSupplier(sdf_file,sanitize=False)
  # iterate over each molecule
  for mol in supplier:
    Chem.SanitizeMol(mol)
    # get lists of ring‐atom indices (0-based)
    rings = mol.GetRingInfo().AtomRings()
    for rdk_ring in rings:
      # convert each rdk ring (0-based) to sdf (1-based)
      sdf_ring = tuple(x + 1 for x in rdk_ring)
      # count aromatic atoms + check if all atoms in the ring are aromatic
      all_arom_check = 0
      for atom in sdf_ring:
          ring_atom = mol.GetAtomWithIdx(int(atom) - 1)
          is_aromatic = ring_atom.GetIsAromatic()
          print(is_aromatic)

          all_arom_check += 1
      if all_arom_check == len(sdf_ring):
        aromatic.append(sdf_ring)
  """
  supplier = Chem.SDMolSupplier(sdf_file,sanitize=False)
  for mol in supplier:
    rings = mol.GetRingInfo().AtomRings()
    for rdk_ring in rings:
      sdf_ring = tuple(x + 1 for x in rdk_ring)

      num_sp2 = 0
      not_arom = 0
      for atom in sdf_ring:
        if str(atom) in sp2:
          num_sp2 += 1
        if str(atom) not in sp2 and str(atom) not in lone:  # all aromatic atoms should be either sp2 or have lone pair
          not_arom += 1
      if num_sp2 >= 3 and not_arom == 0:
        aromatic.append(sdf_ring)
  return aromatic


def planeinfo(A, B, C):
  """
  Compute the circumcenter and plane normal of triangle ABC.

  Parameters
  ----------
  A, B, C : array-like of length 3
      Coordinates of the three points defining the plane.

  Returns
  -------
  vector : ndarray shape (3,)
      Vector from the circumcenter to point A.
  normal : ndarray shape (3,)
      Normal vector of the plane ABC.
  circumcentre : ndarray shape (3,)
      Coordinates of the triangle’s circumcenter.
  """
  AC = A - C
  BC = B - C
  a = np.linalg.norm(AC)
  b = np.linalg.norm(BC)

  # getting a vector perpendicular to plane (cross product)
  cross = np.cross(AC, BC)
  c = np.linalg.norm(cross)
  circumcentre = (np.cross(((a*a)*BC - (b*b)*AC), cross))/(2*c*c) + C

  vector = A - circumcentre # vectors defined with circumcentre as origin
  normal = np.cross(A - circumcentre, B - circumcentre)
  return vector, normal, circumcentre


def pi_score(arom, l_vector, l_normal, l_circumcentre, t_aromatic, t_vectors, t_normals, t_circumcentres):
  """
  Evaluate π‐stacking geometry between one ligand ring and target rings.

  Parameters
  ----------
  arom : tuple
      Atom IDs of the ligand aromatic ring.
  l_vector : ndarray shape (3,)
      Vector from ligand ring circumcenter to one atom.
  l_normal : ndarray shape (3,)
      Plane normal of the ligand ring.
  l_circumcentre : ndarray shape (3,)
      Ligand ring circumcenter coordinates.
  t_aromatic : list of tuples
      Atom ID tuples for each target ring.
  t_vectors : list of ndarray shape (3,)
      Corresponding vectors for each target ring.
  t_normals : list of ndarray shape (3,)
      Plane normals for each target ring.
  t_circumcentres : list of ndarray shape (3,)
      Circumcenters of each target ring.

  Returns
  -------
  score_per_ring : float
      Calculated π‐stacking score (currently always 0.0).
  """
  print_list = []
  stack_count = 0
  l_centre = l_circumcentre
  P = l_vector  # plane vector P
  Q = l_normal  # plane normal Q
  p = np.linalg.norm(P)
  q = np.linalg.norm(Q)
  print_list.append(str(arom) + " (aromatic ring):")
  # iterating over each target ring
  for v in range(len(t_aromatic)):
    t_centre = t_circumcentres[v]
    distance = np.linalg.norm(l_centre - t_centre)
    if distance <= para[8]:
      N = t_normals[v]  # plane normal N
      n = np.linalg.norm(N)

      cos_alpha = np.clip(abs(np.dot(P, N)) / (p*n), 0.0, 1.0)
      alpha = math.acos(cos_alpha) * 180 / math.pi  # angle between plane vector from ligand and normal vector from target
      theta = abs(90.0 - alpha)  # pi stacking angle for parallel systems

      cos_beta = np.clip(abs(np.dot(Q, N)) / (q*n), 0.0, 1.0)
      beta = math.acos(cos_beta) * 180 / math.pi  # angle between plane normal from ligand and normal vector from target + pi stacking angle for edge-to-face systems

      # record a face-to-face interaction
      if theta <= para[9] and distance <= para[7]:
        print_list.append("pi-stacking (face-to-face/parallel-displaced) with " + str(t_aromatic[v]))
        stack_count += 1
      # record an edge-to-face interaction
      if beta >= para[10]:
        print_list.append("pi-stacking (edge-to-face) with " + str(t_aromatic[v]))
        stack_count += 1
  # only print the results if the score_per_ring ever changed
  if stack_count != 0:
    for result in print_list:
      log.write(result + "\n")
  if stack_count == 0:
    print_list.append("no pi-stacking interaction found")
  return stack_count

targetfile = input("macromolecule sdf: ") # sdf file coverted from mol2 through openbabel
f = open(targetfile,"r")


t_atom, t_bond = extract(f,"target")
t_SD, t_ND, t_WD, t_SA, t_NA, t_XX, t_sp2, t_lone = classify(t_atom, t_bond)


t_aromatic = find_ring(targetfile, t_sp2, t_lone)

t_vectors = np.empty((0, 3))
t_normals = np.empty((0, 3))
t_circumcentres = np.empty((0, 3))

for arom in t_aromatic:
    A = np.array([float(t_atom[int(arom[0])-1][2]), float(t_atom[int(arom[0])-1][3]), float(t_atom[int(arom[0])-1][4])])
    B = np.array([float(t_atom[int(arom[1])-1][2]), float(t_atom[int(arom[1])-1][3]), float(t_atom[int(arom[1])-1][4])])
    C = np.array([float(t_atom[int(arom[2])-1][2]), float(t_atom[int(arom[2])-1][3]), float(t_atom[int(arom[2])-1][4])])
    t_vector, t_normal, t_circumcentre = planeinfo(A, B, C)

    t_vectors = np.append(t_vectors, np.array([t_vector]), axis=0)
    t_normals = np.append(t_normals, np.array([t_normal]), axis=0)
    t_circumcentres = np.append(t_circumcentres, np.array([t_circumcentre]), axis=0)


f.close()

"""separate ligands from the dock pose sdf into individual sdfs"""

ligandfile = input("dock pose sdf: ") # sdf file exported from FITTED

e = open(ligandfile,"r")
total_pose = 0  # total number of ligands
keep = 0  # number of ligands kept
list = e.readlines()
list_id = 0

log = open("interaction_search.out","a")
out = open("filtered_poses.sdf","a")

os.mkdir('poses')
for line in list: # for each dock pose
  match = re.search(r"_DockingRun_",line)
  if match:
    total_pose += 1
    name = line.split("_DockingRun_")[0]
    path = './poses/%s.sdf' %name
    j = open(path,'w')
    j.write(line)
    for i in range(10000):
      j.write(list[list_id+i+1])
      if '$$$$' in list[list_id+i+1]:
        break
    j.close()

    a = open(path,'r')
    l_atom, l_bond, l_ring = extract(a,"ligand")
    l_SD, l_ND, l_WD, l_SA, l_NA, l_XX, l_sp2, l_lone = classify(l_atom, l_bond)
    l_aromatic = find_ring(path, l_sp2, l_lone)

    log.write(name + "\n\n")
    log.write("### POLAR_INTERACTION_COUNTER ###\n")
    total_hbond_count, charged_hbond_count, salt_bridge_count, unsatisfied_count = hbond_score(l_atom, t_atom, l_SD, l_ND, l_WD, l_SA, l_NA, l_XX, t_SD, t_ND, t_WD, t_SA, t_NA, t_XX)
    log.write("### total number of polar interactions: " + str(total_hbond_count) + " ###\n")
    log.write("### " + str(charged_hbond_count) + " of them involve one charged group (strong HBDAs and metals) ###\n")
    log.write("### " + str(salt_bridge_count) + " of them are salt-bridges ###\n")
    log.write("### total number of unsatisted HBDAs: " + str(unsatisfied_count) + " ###\n\n")

    log.write("### PI_STACK_COUNTER ###\n")
    total_pi_count = 0
    for arom in l_aromatic:
      A = np.array([float(l_atom[int(arom[0])-1][2]), float(l_atom[int(arom[0])-1][3]), float(l_atom[int(arom[0])-1][4])])
      B = np.array([float(l_atom[int(arom[1])-1][2]), float(l_atom[int(arom[1])-1][3]), float(l_atom[int(arom[1])-1][4])])
      C = np.array([float(l_atom[int(arom[2])-1][2]), float(l_atom[int(arom[2])-1][3]), float(l_atom[int(arom[2])-1][4])])
      l_vector, l_normal, l_circumcentre = planeinfo(A, B, C)
      score_per_ring = pi_score(arom, l_vector, l_normal, l_circumcentre, t_aromatic, t_vectors, t_normals, t_circumcentres)
      total_pi_count += score_per_ring
    log.write("### total number of pi stacking: " + str(total_pi_count) + " ###\n")
    a.close()

    if total_hbond_count >= para[3] and charged_hbond_count >= para[4] and salt_bridge_count >= para[5] and unsatisfied_count <= para[6] and total_pi_count >= para[11]:
      log.write("---------------------------------" + name + " ACCEPTED" + "---------------------------------\n\n")
      keep += 1
      b = open(path,'r')
      for line in b:
        out.write(line)
      b.close()

    else:
      log.write("---------------------------------" + name + " REJECTED" + "---------------------------------\n\n")

    os.remove(path)
  list_id += 1

log.write("\n" + str(keep) + " out of " + str(total_pose) + " ligands were kept\n")
print("program fully executed")

log.close()
out.close()

os.rmdir('poses')
e.close()

