# -*- coding: utf-8 -*-
"""Residue_Targeting_David.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCKbk0vac3-HqSU4Rc8lePTLH7dSenkW
"""

# pip install rdkit

# Commented out IPython magic to ensure Python compatibility.
# %%python "/content/drive/MyDrive/Moitessier Research Group/Shared Code/dock_pose_postprocessing/3fu2_all_Summarized_Results_aggregated.sdf"
# 
# import sys
# 
# if __name__ == '__main__':
#     print(sys.argv)

# David's version, to combine with others

from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdqueries
from rdkit.DataStructs import FingerprintSimilarity
import math
import os
import sys
import matplotlib.pyplot as plt
import numpy as np
import copy
import pandas as pd
import gc

def read_sdf(file_path):
    """Reads an SDF file and returns a list of molecules."""
    suppl = Chem.SDMolSupplier(file_path,sanitize=False)
    #suppl = Chem.SDMolSupplier(file_path)

    # Disable the kekulizition step and perform other sanitization steps
    flags = Chem.SanitizeFlags.SANITIZE_ALL & ~Chem.SanitizeFlags.SANITIZE_KEKULIZE

    molecules = [mol for mol in suppl if mol is not None]
    raw_mols = copy.deepcopy(molecules)
    print(str(len(molecules)) + " molecules in list.")
    for i, mol in reversed(list(enumerate(molecules))):
        print(f"Processing molecule " + str(i) + "...")
        #raw_mols.append(copy.deepcopy(mol))
        print(f"Fixing formal charges...")
        mol = add_formal_charges(mol)
        print(f"Formal charges fixed!")

        print(f"Sanitizing molecule...")
        try:
            Chem.SanitizeMol(mol, sanitizeOps=flags)
            #Chem.SanitizeMol(mol)
            mol = Chem.rdmolops.RemoveAllHs(mol)
            molecules[i] = copy.deepcopy(mol)
            print(molecules[i].GetNumAtoms())
            print(f"Molecule sanitized!")
        except Exception as e:
            print(f"Error sanitizing molecule: {e}")
            print(f"Skipping molecule " + str(i) + "...")
            print(f"Deleting molecule " + str(i) + "...")
            print(f"Molecule " + str(i) + " deleted...")
    print(str(len(molecules)) + " molecules in list.")
    #exit()
    #print(len(molecules))
    #print(len(raw_mols))
    #print(raw_mols[0].GetProp('_Name'), raw_mols[1].GetProp('_Name'))
    return molecules, raw_mols


def calculate_interactions_and_coords(molecule, ref_points):
    """Calculates interactions, coordinates, and distance to ref_point for each atom in a molecule."""
    interactions_coords_dist = []
    conf = molecule.GetConformer()
    count_good = 0
    count_bad = 0
    molecule_interactions = [0] * len(ref_points)
    # Loop over interactions in the binding site
    for ref_point in ref_points:
        site_idx = ref_points.index(ref_point)
        ref_xyz, interaction, weight = ref_point
        ref_x, ref_y, ref_z = ref_xyz
        #print("ref_point is: " + str(ref_point))
        # Loop over atoms in ligand
        anything_else = False
        something = False
        aromatic_atoms = []
        for atom in molecule.GetAtoms():
            atom_idx = atom.GetIdx()
            #print("atom_idx is: " + str(atom_idx))
            coords = conf.GetAtomPosition(atom_idx)
            distance = math.sqrt((coords.x - ref_x) ** 2 + (coords.y - ref_y) ** 2 + (coords.z - ref_z) ** 2)
            if distance > 3.5:
                continue # go to next atom in ligand
            #print("distance = " + str(distance))
            HB_type = getHB_type(atom)
            #print("Atom index " + str(atom_idx) + " has HB_type " + HB_type)
            if interaction == 'hbd':
                if HB_type == 'HBA_only' or HB_type == 'both': # HBD needs HBA
                    favourability = 'Favourable'
                    favourable = True                           #       A favourable Hbond interaction exists
                    something = True                            # Something means an Hbond interaction exists
                elif HB_type == 'HBD_only':
                    favourability = 'Unfavourable'
                    favourable = False
                    something = True
                else:
                    favourable = None
                    anything_else = atom_idx                    # An nonpolar atom is nearby, which would displace water (unfavourable)
            elif interaction == 'hba':
                if HB_type == 'HBD_only' or HB_type == 'both': # HBA needs HBD
                    favourability = 'Favourable'
                    favourable = True
                    something = True
                elif HB_type == 'HBA_only':
                    favourability = 'Unfavourable'
                    favourable = False
                    something = True
                else:
                    favourable = None
                    anything_else = atom_idx
            elif interaction == 'aro': # Aromatic sites
                if distance < 1.5 and atom.GetHybridization() is Chem.rdchem.HybridizationType.SP2: #atom.GetIsAromatic() is True:
                    aromatic_atoms.append(atom_idx)
                continue
            #aromatic = atom.GetAtomicNum not in [6, 1] # i.e. not carbon or hydrogen
            else:
                print(interaction + "Is not a known interaction.")
                favourability = 'Not known'
                anything_else = True
                favourable = None
            if distance < 3.3 and favourable != None:
                #print(favourability + " interaction of distance " + str(round(distance, 2)) + " identified between site " + str(site_idx) + " (" + interaction + ") and atom " + str(atom_idx) + " (" + HB_type + ")")
                interactions_coords_dist.append((site_idx, atom_idx, interaction, coords.x, coords.y, coords.z, favourable))
                if favourable is True:
                    molecule_interactions[site_idx] = 1
                else:
                    molecule_interactions[site_idx] = 0
        if interaction == 'aro':
            #print("Site " + str(site_idx) + " has " + str(len(aromatic_atoms)) + " aromatic atoms nearby: " + str(aromatic_atoms))
            if len(aromatic_atoms) >= 2:
                molecule_interactions[site_idx] = 1
            else:
                molecule_interactions[site_idx] = 0
        elif something is False and anything_else != 9999: # No polar atoms were found, but a non-polar atom was found, which would displace water
            #print("Interaction of type " + interaction + " at site " + str(site_idx) + " is unfulfilled")
            coords = conf.GetAtomPosition(anything_else)
            interactions_coords_dist.append((site_idx, anything_else, interaction, coords.x, coords.y, coords.z, False))
            molecule_interactions[site_idx] = -1
    return molecule_interactions #interactions_coords_dist

def getHB_type(atom):
    #print("line 115", atom.GetSymbol())
    if atom.GetSymbol() in ['N', 'O', 'F', 'S', 'Cl']: # Check if atom is electronegative
        #print(atom.GetSymbol(), Chem.rdchem.HybridizationType.SP2, atom.GetExplicitValence(), atom.GetImplicitValence())
        #print("line 116", atom.GetNumImplicitHs(), atom.GetNumExplicitHs())
        total_valence = atom.GetImplicitValence() + atom.GetExplicitValence()
        #print("Total valence: " + str(total_valence))
        if atom.GetNumImplicitHs() >= 1 or atom.GetNumExplicitHs() >= 1: # check for protons
            #print("POLAR HYDROGEN FOUND!!!!!")
            if atom.GetSymbol() == 'N' and total_valence == 4: # ammonium is not an HBA
                #print("ammonium is HBD only, not an HBA")
                return 'HBD_only'
            # Check for amides, anilines, and pyrroles
            elif atom.GetSymbol() == 'N' and atom.GetHybridization() is Chem.rdchem.HybridizationType.SP2 and total_valence == 3:
                #print("amides, anilines, and pyrroles are HBD only, not HBAs")
                return 'HBD_only'
            else:
                # If not ammonium, amide, or pyrrole, must be both HBD and HBA
                return 'both'
        # If no protons, check for lone pairs
        #print("This heteroatom has no hydrogens, not HBD")
        elif atom.GetSymbol() == 'S' and total_valence == 4: # sulfate sulfur is not an HBA
            #print("sulfate sulfur is not an HBA")
            return 'none'
        else:
            #print("HBA found")
            return 'HBA_only'
    else:
        return 'none'


def write_filtered_molecules(molecules, output_file_path):
    """Writes the filtered molecules to an SDF file."""
    writer = Chem.SDWriter(output_file_path)
    writer.SetKekulize(False)
    i = 0
    for mol in molecules:
        i += 1
        #print("Writing molecule " + str(i) + "...")
        writer.write(mol)
    writer.close()


def add_formal_charges(mol):
    mol.UpdatePropertyCache(strict=False)

    for at in mol.GetAtoms():
        if at.GetAtomicNum() == 7:
            if at.GetExplicitValence() == 4:
                mol.GetAtomWithIdx(at.GetIdx()).SetFormalCharge(1)
                print(' Nitrogen formal charge adjusted ', at.GetFormalCharge(), at.GetIdx())
        if at.GetAtomicNum() == 5:
            if at.GetExplicitValence() == 4:
                mol.GetAtomWithIdx(at.GetIdx()).SetFormalCharge(-1)
                print(' Boron formal charge adjusted ', at.GetFormalCharge(), at.GetIdx())
        if at.GetAtomicNum() == 8:
            if at.GetExplicitValence() == 1:
                mol.GetAtomWithIdx(at.GetIdx()).SetFormalCharge(-1)
                print(' Oxygen formal charge adjusted ', at.GetFormalCharge(), at.GetIdx())
    return mol


def get_lib_id_and_smiles(mol):

    mol_name = mol.GetProp('_Name') if mol.HasProp('_Name') else f'Molecule_{i}'
    mol_lib = mol.GetProp('<Library_Name') if mol.HasProp('<Library_Name') else f'Library unknown'

    # Split by underscore
    split_mol_name = mol_name.split('_')
    library = split_mol_name[0]
    mol_num = int(split_mol_name[1])
    #print(split_mol_name)

    analogue = False
    if library == 'Chemspace':
        file_name = 'Chemspace-RNA_noDuplicates.csv'
        #print('mol_name is: ' + mol_name)
        #print('library is: ' + library)
        #print('file_name is ' + file_name)
    elif library == 'Enamine':
        file_name = 'Enamine-RNA_noDuplicates.csv'
    elif library == 'LifeChemicals':
        file_name = 'LifeChemicals-RNA_noDuplicates.csv'
    elif library == 'MCule':
        file_name = 'MCule-RNA-1_noDuplicates.csv'
    elif library == 'Analogues':
        print("Ah, sh*t! An analogue.")
        print('library is: ' + mol_lib)
        lib_id = mol_lib
        smiles = ''
        analogue = True
        return lib_id, smiles, analogue
    else:
        print("Else clause on or near line 222")
        lib_id = ''
        smiles = ''
        return lib_id, smiles, analogue

    # Read the CSV file into a pandas DataFrame
    #print('file_name is ' + file_name)
    df = pd.read_csv(file_name)
    # Check if the molecule number exists in the ID column
    search_value = mol_num
    search_column = 'Index'
    return_column = 'Smiles'
    if search_value in df[search_column].values:
        # Return the value from the return_column in the same row
        smiles = df.loc[df[search_column] == search_value, return_column].values[0]
    else:
        #print("Value " + str(mol_num) + " not found in ID column")
        smiles = ''
    return_column = 'ID'
    if search_value in df[search_column].values:
        # Return the value from the return_column in the same row
        lib_id = df.loc[df[search_column] == search_value, return_column].values[0]
    else:
        #print("Value " + str(mol_num) + " not found in ID column")
        lib_id = ''
    return lib_id, smiles, analogue


def main(file_path, ref_interacts, output_file_path, csv_file_path, outliers):
    # Read the molecules from the SDF file
    try:
        molecules, raw_mols = read_sdf(file_path)
    except Exception as e:
        print(f"Error reading SDF file: {e}")
        return

    filtered_molecules = []
    filtered_analogues = []
    analogues_from_smiles = []

    try:
        os.remove(csv_file_path)
    except Exception as e:
        print(e)

    # Write CSV header
    line = "Fitted_Molecule_Name,SDF #"
    for i, site in enumerate(ref_interacts):
        line = line + ",Site_" + str(i)
    line = line + ",Score,Library ID,CSV_Smiles,RDkit_Smiles"
    line = line + "\n"
    with open(csv_file_path, "a") as csv_file:
        csv_file.write(line)

    # Find interactions for each molecule
    mol_output_num = 0
    for j, mol in enumerate(molecules):
        file_name = f"aro_coords_{j}.txt"

        # Get molecule name
        mol_name = mol.GetProp('_Name') if mol.HasProp('_Name') else f'Molecule_{j}'
        #print("Processing " + mol_name + "...")

        molecule_interactions = calculate_interactions_and_coords(mol, ref_interacts)

        #print("Saving interactions to csv")
        line = ""
        total = 0
        threshold = 7
        with open(csv_file_path, "a") as csv_file:
            for i, interaction in enumerate(molecule_interactions):
                line = line + "," + str(interaction)               # Append interaction to line
                total = total + interaction * ref_interacts[i][2]   # Compute total
            line = line + "," + str(total)
            if total >= threshold:
                mol_output_num += 1
                #print(molecule_interactions)
                lib_id, csv_smiles, analogue = get_lib_id_and_smiles(mol)

                #try:
                #    # Try to kekulize the molecule (important for SMILES)
                #    Chem.Kekulize(mol)
                #    mol_fewer_hs = Chem.RemoveHs(mol)
                #    rdkit_smiles = Chem.MolToSmiles(mol_fewer_hs, canonical=True)
                #except Chem.rdchem.KekulizeException:
                #    print("Kekulization failed. Proceeding without Kekulization or H removal.")
                #    rdkit_smiles = Chem.MolToSmiles(mol, canonical=True)

                line = mol_name + "," + str(mol_output_num) + line  # Prepend fitted molecule name and output number to line
                line = line + "," + lib_id
                line = line + "," + csv_smiles   # Append the SMILES to line
                #line = line + "," + rdkit_smiles # Append the SMILES to line
                line = line + "\n"
                csv_file.write(line)                                # Append molecule line to file

                #if total >= threshold:
                # Add to output sdf
                #filtered_molecules.append(mol)
                print("j = " + str(j))
                print("mol j is: " + raw_mols[j].GetProp('_Name'))
                filtered_molecules.append(raw_mols[j])

                if analogue:
                    filtered_analogues.append(raw_mols[j])

                    # Import analogues library
                    analogues_csv_filename = lib_id + "-Entire-Library_noDuplicates.csv"
                    print("Loading " + analogues_csv_filename + "...")
                    analogues_df = pd.read_csv(analogues_csv_filename)
                    print(analogues_df)

                    #print("Converting Smiles to Mol...")
                    #analogues_df['Mol'] = analogues_df['Smiles'].apply(Chem.MolFromSmiles)

                    # Filter by carbon count
                    carbon_query = rdqueries.AtomNumEqualsQueryAtom(6)
                    carbon_count = len(mol.GetAtomsMatchingQuery(carbon_query))
                    print(mol_name + " has " + str(carbon_count) + " carbons")
                    print("Filtering " + lib_id + " library by carbon...")
                    analogues_df = analogues_df[analogues_df['Smiles'].apply(
                        lambda smiles: len(Chem.MolFromSmiles(smiles).GetAtomsMatchingQuery(carbon_query))
                        if Chem.MolFromSmiles(smiles) else 0) == carbon_count]
                    print(analogues_df)
                    print(str(len(analogues_df.index)) + " molecules remain in the " + lib_id + " library")

                    # Filter by nitrogen count
                    nitrogen_query = rdqueries.AtomNumEqualsQueryAtom(7)
                    nitrogen_count = len(mol.GetAtomsMatchingQuery(nitrogen_query))
                    print(mol_name + " has " + str(nitrogen_count) + " nitrogens")
                    print("Filtering " + lib_id + " library by nitrogen...")
                    analogues_df = analogues_df[analogues_df['Smiles'].apply(
                        lambda smiles: len(Chem.MolFromSmiles(smiles).GetAtomsMatchingQuery(nitrogen_query))
                        if Chem.MolFromSmiles(smiles) else 0) == nitrogen_count]
                    print(analogues_df)
                    print(str(len(analogues_df.index)) + " molecules remain in the " + lib_id + " library")

                    # Filter by oxygen count
                    oxygen_query = rdqueries.AtomNumEqualsQueryAtom(8)
                    oxygen_count = len(mol.GetAtomsMatchingQuery(oxygen_query))
                    print(mol_name + " has " + str(oxygen_count) + " oxygens")
                    print("Filtering " + lib_id + " library by oxygen...")
                    analogues_df = analogues_df[analogues_df['Smiles'].apply(
                        lambda smiles: len(Chem.MolFromSmiles(smiles).GetAtomsMatchingQuery(oxygen_query))
                        if Chem.MolFromSmiles(smiles) else 0) == oxygen_count]
                    print(analogues_df)
                    print(str(len(analogues_df.index)) + " molecules remain in the " + lib_id + " library")

                    # Filter by fluorine count
                    fluorine_query = rdqueries.AtomNumEqualsQueryAtom(9)
                    fluorine_count = len(mol.GetAtomsMatchingQuery(fluorine_query))
                    print(mol_name + " has " + str(fluorine_count) + " fluorine")
                    print("Filtering " + lib_id + " library by fluorine...")
                    analogues_df = analogues_df[analogues_df['Smiles'].apply(
                        lambda smiles: len(Chem.MolFromSmiles(smiles).GetAtomsMatchingQuery(fluorine_query))
                        if Chem.MolFromSmiles(smiles) else 0) == fluorine_count]
                    print(analogues_df)
                    print(str(len(analogues_df.index)) + " molecules remain in the " + lib_id + " library")

                    # Filter by sulfur count
                    sulfur_query = rdqueries.AtomNumEqualsQueryAtom(16)
                    sulfur_count = len(mol.GetAtomsMatchingQuery(sulfur_query))
                    print(mol_name + " has " + str(sulfur_count) + " sulfur")
                    print("Filtering " + lib_id + " library by sulfur...")
                    analogues_df = analogues_df[analogues_df['Smiles'].apply(
                        lambda smiles: len(Chem.MolFromSmiles(smiles).GetAtomsMatchingQuery(sulfur_query))
                        if Chem.MolFromSmiles(smiles) else 0) == sulfur_count]
                    print(analogues_df)
                    print(str(len(analogues_df.index)) + " molecules remain in the " + lib_id + " library")

                    print("Converting Smiles to Mol...")
                    analogues_df['Mol'] = analogues_df['Smiles'].apply(Chem.MolFromSmiles)

                    analogue_output_filename = "similar_" + mol_name + ".sdf"
                    with Chem.SDWriter(analogue_output_filename) as writer:
                        for _, row in analogues_df.iterrows():
                            analogue_mol = row['Mol']
                            if analogue_mol:  # Ensure the Mol object is valid
                                analogue_mol.SetProp('_Name', row['ID'])  # Set the molecule's name

                                #fp1 = AllChem.GetMorganFingerprint(analogue_mol, radius=2) # Fingerprint for the molecule in the dataframe
                                #fp2 = AllChem.GetMorganFingerprint(mol, radius=2)          # Fingerprint of the molecule we're trying to find

                                # Generate binary fingerprints
                                fp1 = AllChem.GetMorganFingerprintAsBitVect(analogue_mol, radius=2, nBits=2048)  # 2048-bit fingerprint
                                fp2 = AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048)

                                # Compute Tanimoto similarity
                                tanimoto = FingerprintSimilarity(fp1, fp2)
                                print("Tanimoto is: " + str(tanimoto))
                                analogue_mol.SetProp('Tanimoto', str(tanimoto))  # Print the tanimoto as a field in the sdf
                                writer.write(analogue_mol)
                    del analogues_df
                    gc.collect()

    # Sort the CSV
    # Load the CSV file
    df = pd.read_csv(csv_file_path)
    # Sort the DataFrame by Score
    #df_sorted = df.sort_values(by='Score', ascending=False)
    df_sorted = df.sort_values(by='SDF #')
    # Save the sorted DataFrame back to a CSV file (optional)
    df_sorted.to_csv(csv_file_path, index=False)

    # Plot the histogram
    #bins = np.arange(min(donnees), max(donnees) + 2) - 0.5
    #hist_values, bin_edges, patches = plt.hist(donnees, bins=bins, edgecolor='black', width = 1, align='mid')
    #for value, patch in zip(hist_values, patches):
    #    plt.text(patch.get_x() + patch.get_width() / 2, value, int(value), ha='center', va='bottom')

    # Write filtered molecules to a new SDF file
    write_filtered_molecules(filtered_molecules, output_file_path)
    print(str(len(filtered_molecules)) + " Molecules in filtered set")
    print(f"Filtered molecules have been written to {output_file_path}")

    write_filtered_molecules(filtered_analogues, "filtered_analogues.sdf")

if __name__ == "__main__":
    # Replace 'Docking-test.sdf' with the path to your SDF file
    #sdf_file_path = '3fu2_Chemspace_Summarized_Results_aggregated.sdf' # Enter your SDF name here !!!
    try:
        input_file = sys.argv[1]
    except IndexError:
        print("Please specify sdf file as argument")
        exit()
    sdf_path = input_file
    filename, file_extension = os.path.splitext(sdf_path)

    # List of interactions for PreQ1 riboswitch

    interactions_list = []
    # CYT 17 O  HBA, needs HBD
    interactions_list.append(((-10.87, -6.77, -21.37), 'hba', 1))
    # CYT 17 N  HBA, needs HBD
    interactions_list.append(((-13.08, -6.26, -21.31), 'hba', 1))
    # CYT 17 NH HBD, needs HBA
    interactions_list.append(((-15.31, -5.79, -21.30), 'hbd', 2)) # Conserved across 3fu2 and 8yam
    # ADO 30 N  HBA, needs HBD
    interactions_list.append(((-8.30, -7.84, -16.76), 'hba', 1))
    # ADO 30 N  HBD, needs HBA
    interactions_list.append(((-8.86, -6.39, -15.06), 'hbd', 2))  # Conserved across 3fu2 and 8yam
    # URA  6 O  HBA, needs HBD
    interactions_list.append(((-10.80, -6.46, -12.64), 'hba', 1))
    # GUA  5 N  HBA, needs HBD
    interactions_list.append(((-17.44, -6.37, -13.05), 'hba', 1))
    # Aromatic center 1
    interactions_list.append(((-12.82, -5.48, -17.08), 'aro', 2))
    # Aromatic center 2
    interactions_list.append(((-13.74, -4.86, -15.22), 'aro', 2))

    #file stuff
    output_sdf_path = filename + '_filtered.sdf' # The name of your output
    csv_file_path = filename + '_plot.png'
    csv_file_path = filename + '_filtered.csv'
    outliers = 'outliers.txt'
    main(input_file, interactions_list, output_sdf_path, csv_file_path, outliers)
# This is the last line of the file